### PR TITLE
Cleanup (Eclipse files, encoding, line separators)

### PR DESCRIPTION
**Pull request by recena**
- [x] Remove Eclipse files
- [x] Add README.md file
- [x] Set UTF-8 file enconding (`pom.xml`)
- [x] Unify line separators

@orrc What do you think? Do you agree?

### CODE REVIEW

**Comment by orrc** [comment]
These changes were made against master, instead of against your workflow branch, so this patch doesn't apply usefully: the POM has two `<properties>` tags, and `LintMavenResultAction` has the non-workflow code.

I've removed the Eclipse files, updated the POM and added a README myself.

**Comment by recena** [comment]
@orrc It is normal to do this againt `master`. Where was the problem?

**Comment by recena** [comment]
@orrc I did that in a different PR because you prefered this ways.

**Comment by orrc** [comment]
It's also fine to submit a patch against a branch, if you rely on the changes in it.

The problem was described already: this patch doesn't apply against master @ec7b381 — the project cannot be compiled as the POM has two `<properties>` tags, and `LintMavenResultAction` cannot be merged.

**Comment by recena** [comment]
@orrc I understand. Thanks.

**Pull request closed without merging**
