### PR TITLE
[FIXED JENKINS-34621] Missing lint graph when using with Pipeline plugin

### PR DESCRIPTION
**Pull request by warnyul**
Fix for this issue:
https://issues.jenkins-ci.org/browse/JENKINS-34621

I left some comments under the issue.

### CODE REVIEW

**Comment by mtrakal** [comment]
@orrc could you please merge it? It loks that almost solve issue with missing chart for pipeline. I know, that it have some issue with trend line, but it's still better have some chart, that no chart.

**Comment by nezero** [comment]
Any chance of a merge? It would be nice to have this back!

**Comment by orrc** [comment]
Sorry. I'll get on it soon once I'm done travelling. Thanks for the reminders!

**Comment by warnyul** [comment]
I updated my PR. I updated analysis-core to 1.87 from 1.84, that solved linking problems in the dashboard view.

**Comment by AkshayPathak** [comment]
@orrc Can we please get a merge on this PR?

**Comment by orrc** [comment]
Yup, I've been working on testing it.

**Comment by orrc** [comment]
Thanks. I've merged this to `master`, and done some additional updates — the latest build can be found here: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fandroid-lint-plugin/detail/master/1/artifacts

I'm just waiting for a couple of dependent build plugins to be upgraded so that a release can be done.

**Comment by orrc** [comment]
Version 2.5 of the plugin has been released.

**Pull request closed without merging**
